### ISSUE TITLE
Melhoria na responsividade

### ISSUE THREAD

**Issue by cts93** [RossanaSena/Product-preview-card-component#1]
Oi, Rossana! Parabéns pelo projeto. Acho que agregaria muito se na versão **mobile** a descrição do produto ficasse posicionada abaixo da imagem; e abaixo do texto, o preço e o botão de comprar. A assinatura do projeto (seu nome) também poderia ficar no rodapé, ou no topo com menor destaque.

A dica que te dou (agora que pensei também servirá pra mim) é entrar em sites de e-commerce como Netshoes e se inspirar no layout, tanto de desktop quanto mobile (através das ferramentas de desenvolvedor).

Abraço e bons projetos!

**Comment by RossanaSena** [comment]
Oie Carlos! Ainda não cheguei na versão mobile, mas vou me atentar às suas colocações. Agradeço pelo seu tempo em analisar o projeto e deixar ótimas observações.
